fastlane_version '2.113.0'

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

# iOS Lanes
platform :ios do
  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(
      app_identifier: 'com.crowdbotics.{{cookiecutter.project_slug}}',
      type: 'development',
      readonly: true
    )
    match(
      app_identifier: 'com.crowdbotics.{{cookiecutter.project_slug}}',
      type: 'appstore',
      readonly: true
    )
  end

  desc 'Build the iOS application.'
  private_lane :build do
    certificates
    increment_build_number(xcodeproj: './ios/{{cookiecutter.project_slug}}.xcodeproj')
    gym(
      scheme: '{{cookiecutter.project_slug}}',
      project: './ios/{{cookiecutter.project_slug}}.xcodeproj'
    )
  end

  desc 'Ship to Testflight.'
  lane :beta do
    build
    pilot
    commit_version_bump(message: 'Bump iOS build', xcodeproj: './ios/name.xcodeproj')
    push_to_git_remote
  end
end

# Android Lanes
platform :android do
  desc 'Build the Android application.'
  private_lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'incrementVersionCode', project_dir: 'android/')
  end

  desc 'Ship to Playstore Beta.'
  lane :beta do
    build
    supply(track: 'beta', track_promote_to: 'beta')
    git_commit(path: ['./android/gradle.properties'], message: 'Bump Android versionCode')
    push_to_git_remote
  end
end
